{% set name = "VISIBLE" %}
{% set version = "0.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "3f3df3a99a29be4226817325541f71697399dfa7672a5fdad2db46f9ebb24c83" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://files.pythonhosted.org/packages/75/d7/0a11adc9f409932ae77b0186686ac6bb54b781073f3d51b0f25a990397a9/VISIBLE-0.1.0.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - python >=2.7.0
    - numpy >=1.13.1
    - scipy >=0.19.1
    - astropy >=2.0.0
    - matplotlib >=2.1.0
    - casacore >=2.4.0
    - casa-python >=5.1.0
    - vis_sample >=0.2.2
  run:
    - python
    - python >=2.7.0
    - numpy >=1.13.1
    - scipy >=0.19.1
    - astropy >=2.0.0
    - matplotlib >=2.1.0
    - casacore >=2.4.0
    - casa-python >=5.1.0
    - vis_sample >=0.2.2

test:
  imports:
    - VISIBLE

about:
  home: https://github.com/AstroChem/vis_sample
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Interferometric matched filtering
  description: "The matched_filter() method in VISIBLE allows you to apply an approximated matched filter to interferometric spectral line data and extract a signal.\n    "
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
